<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Select extends Seeder
{
    public function run()
    {
        $pilih_data = [
            ['nomor' => '1', 'param' => 'sistemsusut', 'nama' => 'garislurus',],
            ['nomor' => '2', 'param' => 'sistemsusut', 'nama' => 'saldoturun',],
            ['nomor' => '1', 'param' => 'katakun', 'nama' => '1harta',],
            ['nomor' => '2', 'param' => 'katakun', 'nama' => '2kewajiban',],
            ['nomor' => '3', 'param' => 'katakun', 'nama' => '3modal',],
            ['nomor' => '4', 'param' => 'katakun', 'nama' => '4pendapatan',],
            ['nomor' => '5', 'param' => 'katakun', 'nama' => '5hpp',],
            ['nomor' => '6', 'param' => 'katakun', 'nama' => '6biaya',],
            ['nomor' => '7', 'param' => 'katakun', 'nama' => '7pendapatanlain',],
            ['nomor' => '8', 'param' => 'katakun', 'nama' => '8biayalain',],
            ['nomor' => '1', 'param' => 'goldarah', 'nama' => 'A',],
            ['nomor' => '2', 'param' => 'goldarah', 'nama' => 'B',],
            ['nomor' => '3', 'param' => 'goldarah', 'nama' => 'AB',],
            ['nomor' => '4', 'param' => 'goldarah', 'nama' => 'O',],
            ['nomor' => '1', 'param' => 'ijasah', 'nama' => 'SD',],
            ['nomor' => '2', 'param' => 'ijasah', 'nama' => 'SMP',],
            ['nomor' => '3', 'param' => 'ijasah', 'nama' => 'SMU',],
            ['nomor' => '4', 'param' => 'ijasah', 'nama' => 'D3',],
            ['nomor' => '5', 'param' => 'ijasah', 'nama' => 'S1',],
            ['nomor' => '6', 'param' => 'ijasah', 'nama' => 'S2',],
            ['nomor' => '1', 'param' => 'statijasah', 'nama' => 'tahan',],
            ['nomor' => '2', 'param' => 'statijasah', 'nama' => 'kembali',],
            ['nomor' => '1', 'param' => 'statpegawai', 'nama' => 'PKWT',],
            ['nomor' => '2', 'param' => 'statpegawai', 'nama' => 'PKWTT',],
            ['nomor' => '3', 'param' => 'statpegawai', 'nama' => 'PHL',],
            ['nomor' => '1', 'param' => 'modkeluar', 'nama' => 'undurdiri',],
            ['nomor' => '2', 'param' => 'modkeluar', 'nama' => 'phk',],
            ['nomor' => '3', 'param' => 'modkeluar', 'nama' => 'pecat',],
            ['nomor' => '4', 'param' => 'modkeluar', 'nama' => 'pensiun',],
            ['nomor' => '1', 'param' => 'beban', 'nama' => 'proyek',],
            ['nomor' => '2', 'param' => 'beban', 'nama' => 'camp',],
            ['nomor' => '3', 'param' => 'beban', 'nama' => 'alat',],
            ['nomor' => '4', 'param' => 'beban', 'nama' => 'tanah',],
            ['nomor' => '5', 'param' => 'beban', 'nama' => 'tool',],
            // ['nomor' => '1', 'param' => 'bebanum', 'nama' => 'proyek',],
            // ['nomor' => '2', 'param' => 'bebanum', 'nama' => 'camp',],
            // ['nomor' => '3', 'param' => 'bebanum', 'nama' => 'alat',],
            // ['nomor' => '4', 'param' => 'bebanum', 'nama' => 'tanah',],
            // ['nomor' => '5', 'param' => 'bebanum', 'nama' => 'uangjalan',],
            // ['nomor' => '6', 'param' => 'bebanum', 'nama' => 'kasbon',],
            // ['nomor' => '1', 'param' => 'bebanitem', 'nama' => 'proyek',],
            // ['nomor' => '2', 'param' => 'bebanitem', 'nama' => 'camp',],
            // ['nomor' => '3', 'param' => 'bebanitem', 'nama' => 'alat',],
            // ['nomor' => '4', 'param' => 'bebanitem', 'nama' => 'tanah',],
            // ['nomor' => '5', 'param' => 'bebanitem', 'nama' => 'inventaris',],
            ['nomor' => '1', 'param' => 'itemso', 'nama' => 'item',],
            ['nomor' => '2', 'param' => 'itemso', 'nama' => 'alat',],
            ['nomor' => '3', 'param' => 'itemso', 'nama' => 'tanah',],
            ['nomor' => '4', 'param' => 'itemso', 'nama' => 'inventaris',],
            ['nomor' => '1', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'mintabarang',],
            ['nomor' => '2', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'ambilbarang',],
            ['nomor' => '3', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'keluargudang',],
            ['nomor' => '4', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'pesanbarang',],
            ['nomor' => '5', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kaslangsung',],
            ['nomor' => '6', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kasum',],
            ['nomor' => '7', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kaspindah',],
            ['nomor' => '8', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kasnonlangsung',],
            ['nomor' => '9', 'param' => 'formulir', 'kelompok' => 'penjualan', 'nama' => 'pesanjual',],
            ['nomor' => '10', 'param' => 'formulir', 'kelompok' => 'penjualan', 'nama' => 'pesansewa',],
            ['nomor' => '11', 'param' => 'formulir', 'kelompok' => 'cuti', 'nama' => 'cuti',],
            ['nomor' => '12', 'param' => 'formulir', 'kelompok' => 'anggaran', 'nama' => 'anggaranproyek',],
            ['nomor' => '13', 'param' => 'formulir', 'kelompok' => 'anggaran', 'nama' => 'anggaranobjek',],
            ['nomor' => '1', 'param' => 'akungrup', 'kelompok' => 'aset', 'nama' => 'alat',],
            ['nomor' => '2', 'param' => 'akungrup', 'kelompok' => 'aset', 'nama' => 'tanah',],
            ['nomor' => '3', 'param' => 'akungrup', 'kelompok' => 'aset', 'nama' => 'inventaris',],
            ['nomor' => '4', 'param' => 'akungrup', 'kelompok' => 'stok', 'nama' => 'item',],
            ['nomor' => '5', 'param' => 'akungrup', 'kelompok' => 'stok', 'nama' => 'bahan',],
            ['nomor' => '6', 'param' => 'akungrup', 'kelompok' => 'penerima', 'nama' => 'pegawai',],
            ['nomor' => '7', 'param' => 'akungrup', 'kelompok' => 'penerima', 'nama' => 'pelanggan',],
            ['nomor' => '8', 'param' => 'akungrup', 'kelompok' => 'penerima', 'nama' => 'suplier',],
            ['nomor' => '9', 'param' => 'akungrup', 'kelompok' => 'penerima', 'nama' => 'subkon',],
            ['nomor' => '1', 'param' => 'akunpajak', 'kelompok' => 'pajak', 'nama' => 'ppn',],
            ['nomor' => '2', 'param' => 'akunpajak', 'kelompok' => 'pajak', 'nama' => 'pph',],
            ['nomor' => '3', 'param' => 'akunpajak', 'kelompok' => 'pajak', 'nama' => 'lain',],
            ['nomor' => '1', 'param' => 'akunkas', 'kelompok' => 'kas', 'nama' => 'kas',],
            ['nomor' => '2', 'param' => 'akunkas', 'kelompok' => 'kas', 'nama' => 'bank',],
            ['nomor' => '1', 'param' => 'sim', 'kelompok' => 'SIM A', 'nama' => 'SIM A',],
            ['nomor' => '2', 'param' => 'sim', 'kelompok' => 'SIM A', 'nama' => 'SIM A Umum',],
            ['nomor' => '3', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BI',],
            ['nomor' => '4', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BI Umum',],
            ['nomor' => '5', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BII',],
            ['nomor' => '6', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BII Umum',],
            ['nomor' => '7', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM C',],
            ['nomor' => '8', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM CI Umum',],
            ['nomor' => '9', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM CII',],
            ['nomor' => '10', 'param' => 'sim', 'kelompok' => 'SIM D', 'nama' => 'SIM D',],
            ['nomor' => '11', 'param' => 'sim', 'kelompok' => 'SIM D', 'nama' => 'SIM DI',],
            ['nomor' => '1', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/0',],
            ['nomor' => '2', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/1',],
            ['nomor' => '3', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/2',],
            ['nomor' => '4', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/3',],
            ['nomor' => '5', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/0',],
            ['nomor' => '6', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/1',],
            ['nomor' => '7', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/2',],
            ['nomor' => '8', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/3',],
            ['nomor' => '9', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/0',],
            ['nomor' => '10', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/1',],
            ['nomor' => '11', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/2',],
            ['nomor' => '12', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/3',],
            ['nomor' => '1', 'param' => 'konfigurasi', 'nama' => 'jlsetuju',],
            ['nomor' => '2', 'param' => 'konfigurasi', 'nama' => 'cariharga',],
            ['nomor' => '1', 'param' => 'aksiproses', 'nama' => 'terima',],
            ['nomor' => '2', 'param' => 'aksiproses', 'nama' => 'revisi',],
            ['nomor' => '3', 'param' => 'aksiproses', 'nama' => 'tolak',],
            ['nomor' => '1', 'param' => 'kelin', 'nama' => 'industri',],
            ['nomor' => '2', 'param' => 'kelin', 'nama' => 'nonindustri',],
            ['nomor' => '3', 'param' => 'kelin', 'nama' => 'subkon',],
            ['nomor' => '1', 'param' => 'trip', 'nama' => 'bbm',],
            ['nomor' => '2', 'param' => 'trip', 'nama' => 'honor',],
            ['nomor' => '3', 'param' => 'trip', 'nama' => 'byantri',],
            ['nomor' => '4', 'param' => 'trip', 'nama' => 'lemburbiasa',],
            ['nomor' => '5', 'param' => 'trip', 'nama' => 'lemburbesar',],
            ['nomor' => '6', 'param' => 'trip', 'nama' => 'uangmakan',],
            ['nomor' => '1', 'param' => 'bentuk', 'nama' => 'alatberat',],
            ['nomor' => '2', 'param' => 'bentuk', 'nama' => 'alatindustri',],
            ['nomor' => '3', 'param' => 'bentuk', 'nama' => 'truk',],
            ['nomor' => '4', 'param' => 'bentuk', 'nama' => 'mobil',],
            ['nomor' => '1', 'param' => 'setanggaran', 'nama' => 'pendapatan',],
            ['nomor' => '2', 'param' => 'setanggaran', 'nama' => 'pengeluaran',],
            ['nomor' => '1', 'param' => 'kbli', 'nama' => 'dokumenref',],
            ['nomor' => '2', 'param' => 'kbli', 'nama' => 'objekpajak',],
            ['nomor' => '3', 'param' => 'kbli', 'nama' => 'kbli',],
        ];

        foreach ($pilih_data as $data) {
            $this->db->table('m_select')->insert($data);
        }
    }
}
// php spark db:seed